export const colors = [
    { letter: "a", color: "#FF5733" },
    { letter: "b", color: "#33FF57" },
    { letter: "c", color: "#3357FF" },
    { letter: "d", color: "#F1C40F" },
    { letter: "e", color: "#9B59B6" },
    { letter: "f", color: "#E74C3C" },
    { letter: "g", color: "#1ABC9C" },
    { letter: "h", color: "#2ECC71" },
    { letter: "i", color: "#3498DB" },
    { letter: "j", color: "#9B59B6" },
    { letter: "k", color: "#34495E" },
    { letter: "l", color: "#16A085" },
    { letter: "m", color: "#27AE60" },
    { letter: "n", color: "#2980B9" },
    { letter: "o", color: "#8E44AD" },
    { letter: "p", color: "#2C3E50" },
    { letter: "q", color: "#F39C12" },
    { letter: "r", color: "#D35400" },
    { letter: "s", color: "#C0392B" },
    { letter: "t", color: "#BDC3C7" },
    { letter: "u", color: "#7F8C8D" },
    { letter: "v", color: "#E67E22" },
    { letter: "w", color: "#ECF0F1" },
    { letter: "x", color: "#95A5A6" },
    { letter: "y", color: "#D35400" },
    { letter: "z", color: "#C0392B" },
  ];
  